# These steps should only run on `sandbox.jl` machines, not `docker`-isolated ones
# since we need nestable sandboxing.  The rootfs images being used here are built from
# the `.buildkite/rootfs_images/llvm-passes.jl` file.
agents:
  queue: "julia"
  # Only run on `sandbox.jl` machines (not `docker`-isolated ones) since we need nestable sandboxing
  sandbox.jl: "true"
  os: "linux"

steps:
  - label: "doctest"
    key: doctest
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v1/llvm-passes.tar.gz
          rootfs_treehash: "f3ed53f159e8f13edfba8b20ebdb8ece73c1b8a8"
          uid: 1000
          gid: 1000
          workspaces:
            # Include `/cache/repos` so that our `git` version introspection works.
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- Build Julia from source"
      make -j 6

      echo "--- Print Julia version info"
      ./julia -e 'using InteractiveUtils; InteractiveUtils.versioninfo()'

      echo "--- Build Julia docs"
      make docs

      echo "--- Run Julia doctests"
      JULIA_NUM_THREADS=1 make -C doc doctest=true
    timeout_in_minutes: 120
    notify:
      - github_commit_status:
          context: "doctest"
